language: node_js
node_js: 16

branches:
  only:
    - main
    - /^v\d+\.\d+\.\d+$/

stages:
  - name: test
    if: tag IS blank
  - name: deploy

before_install:
  - git config --local user.name "LTO Network"
  - git config --local user.email "info@ltonetwork.com"
install:
  - npm install

jobs:
  fast_finish: true
  include:
    - name: "Test"
      stage: test
      script:
        - npm test
    - name: "Publish GitHub release"
      stage: deploy
      if: branch = main AND type = push
      before_script:
        - CURRENT_VERSION=$(git describe --tags --abbrev=0)
        - |
          if (git log $CURRENT_VERSION..HEAD | grep -q -i "\[bump:major\]"); then
            NEXT_VERSION=$(awk -F. -v OFS=. '{$1++;$2=0;$3=0;print}' <<< "$CURRENT_VERSION")
          elif (git log $CURRENT_VERSION..HEAD | grep -q -i "\[bump:minor\]"); then
            NEXT_VERSION=$(awk -F. -v OFS=. '{$2++;$3=0;print}' <<< "$CURRENT_VERSION")
          else
            NEXT_VERSION=$(awk -F. -v OFS=. '{$3++;print}' <<< "$CURRENT_VERSION")
          fi
      script:
        - git tag "$NEXT_VERSION"
      before_deploy:
        - npm run build
      deploy:
        provider: releases
        api_key:
          secure: "gldIHb1TGdKKn/xjYek1Rre97El8u/uM/ab8rREF0nYO0phKPRZObSbqaOh9w5222aS04foebJNk3Vh2vFquZSjHFvOOdYAx1BmiHkprNiYNs5refodbcEdTfc3gXs4rs2r55a5PO2JC81OblLZ5URnWAfJefBd6f77siD0x6Cda8YRTh2mC9Gb4Yu2u16BzY1hXfCg5Sg/Cbw63LzjHwRN6kordrpsJrDb4xAqhJ+X1YGZj3oobJOTrtbtlrGTeO7s5nOwnmdi2tKIrFhpIVhsG6ieXXzwguOLpyaIC/hVH6jI7NgyTzojRunUl9QesWdb8rqwssI3/AiEWAdhVQk6xcxgrV9vdFaqRh6qM6GPcO4CGyI3FSSqBGMjbhYWMvMYtTrzM9ucbjBTTNXPOGSaRALZpwD29EB+8pUNCCfmLaNt06H7/au9O5k5z/QmCPd0zodyboe7RiTtG5ikG376wpNG5cwQWVbZgdgcmA8Lb8xhqWWO48kTpbxzSDr3r0dAcKXEKuqvM9DrpQoMnyNkl5GyI4Sqnyv3+7p3+Tb1gq4jEjzBBQs+imNJQeDi6xooEMWZeSoUXQsg+HMUO2bUVFV3OJmCJni5wlvXJnrC+wK4z4QluxMlu9s9WzO/FLUINjDV3U3ojRurV5oCTz3d5LuAIAOSHrH8aI1Be3vQ="
        cleanup: false
        skip_cleanup: true
        on:
          all_branches: true
        file_glob: true
        file: dist/*
    - name: "Publish to NPM"
      stage: deploy
      if: tag IS present
      before_install:
        - npm version $TRAVIS_TAG --no-git-tag-version
      script:
        - npx tsc
      deploy:
        provider: npm
        email: arnold@jasny.net
        api_key:
          secure: "c1bUo1kTPLLWq35Nt4HLfCPAn6gCp3hnDxpRz/FVg1TNk4KAinvDSgM9KoLRIBqxVgEmSMq7EulnkBAjD6iK2wpiBvhPOZHPnhATog75fedG2C11eloK7QgmLUxRhMDrXMnI6qGVsJegdiwHclbG4guIOjqGeSlMq8dgJgWJz2YQr2htFXsaWZZuAoBfOTr+FPqmj/ttFV3U2YNvLKRdISDu3O3FsT19/eNTy7CSLiuNAttqV7/vf683VT+dBrkPAGvfFS6boOCKCgTAtYoLAt5XPgLSlxZDXJOZLF28I0pAwbUQ8pbI8mvw91YJKCbpfdbRdl3RU2DwanDO9pxljuWMD+o0/LkO7kwhYWXHmBL+H4dGXUyE31vxpBGuCUP6X7sde5r7Z01GNxkzLh2gB1tcRj6bCt8VgbeKgl0kX8OfY2AzoeUwokqJbY618KdMz6PsETnrEo9rKnwugDXpGdbz4Nau8HqfoB0+T/R0Or3TFP69rx0Fz4qPvI+xGn+psvjBYxzt0HfMcJJXoBNXIXvFavbveHGbwcOxLEEz24HgA9K7KnMYIr+1nGvqI3w+PwirfM78DRayq7JENbcDH+Ib42tz8PHya7r0V5SjZVHdGt2c/07cm1RPAUhx2D31Tra7VBg8ls2K0/J5S+HCPce5lfkclyDSonkn1a1BNKs="
        on:
          tags: true
        cleanup: false
        skip_cleanup: true
